### ISSUE TITLE
Some elements overlaps when using eminiarts/nova-tabs

### ISSUE THREAD

**Issue by TheSETJ** [pishran/nova-rtl-theme#10] opened 2020-12-13 05:49 UTC
Hey, thanks for your great package.

To make my resource more compact, I installed [eminiarts/nova-tabs](https://github.com/eminiarts/nova-tabs) package to make use of tabs for my relationships. Based on screenshots on [the package's page](https://github.com/eminiarts/nova-tabs#relationship-tabs):

![image](https://user-images.githubusercontent.com/10893088/102004080-c5b3a800-3d22-11eb-948a-f31dbddfff1a.png)

And the fact that I'm using a package for making things RTL, I expected something like the following outcome:

![image](https://user-images.githubusercontent.com/10893088/102004348-1fb56d00-3d25-11eb-9946-b6c6dee3b5c8.png)

But here is how it actually looks:

![image](https://user-images.githubusercontent.com/10893088/102004252-432be800-3d24-11eb-9f19-8ce8dfb089cb.png)

I'm not really good at styling and that's why I don't make a PR (I've managed to get to my expected outcome using some try and failure with inline styling). I hope it gets fixed soon.

I'm using v1.5.3 of your package and v3.14.0 of Laravel Nova.

**Comment by FaridAghili** [comment] 2020-12-14 17:31
Hi,
I never used nova-tabs package and I'm not able to reproduce your issue.

Show some code so I can test it.

**Comment by TheSETJ** [comment] 2020-12-21 06:27
@FaridAghili Here you are:

https://github.com/TheSETJ/laravel-nova-overlapping-elements-using-nova-rtl-theme-and-nova-tabs

I didn't put effort into translation. By the way, the overlapping will be visible on a user's detail page.

**Comment by FaridAghili** [comment] 2020-12-21 23:18
Thank you, I'll give it a try this weekend.
________________________________

**Comment by FaridAghili** [comment] 2021-01-12 10:47
@TheSETJ Fixed in [v1.5.5](https://github.com/pishran/nova-rtl-theme/releases/tag/v1.5.5)

**Closed as completed** 2021-01-14 10:49 UTC
Labels: enhancement, help wanted
